image: node:22

stages:
  - deploy

deploy-pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - rm -rf public
    - mv dist public

  artifacts:
    paths:
      - public

  pages: true

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'